### ISSUE TITLE
Server Sync and Teams

### ISSUE THREAD

**Issue by WanderLanz** [shedaniel/HQM#10]
On AOF3 2.0.2 server with the 1.16 version of HQM, once you make a paty/team, it somehow deletes all quests data and quests data list from data.json in the remote config files and adds them to the teams.json. It leaves the quest data in the each modname.json. In-game, no quests show in the book, so even though I don't have any knowledge of this kinda stuff it seems like we need the quests data in data.json?. Is this intentional or is there an easy way to fix this? They have also tried deleting parties and player data on the server to fix, so maybe it has something to do with server sync or maybe there is another HQM file they are missing? Sorry if this is a dumb question that has already been solved.

**Comment by shedaniel** [comment]
Should be fixed with HQM 0.3.0, please report any issues with it. 0.3.0 will require both the server and client to update.

**Comment by WanderLanz** [comment]
Sounds great! Thank you so much for your time. I hope it wasn't too tedious.
