### ISSUE TITLE
Crashing on server

### ISSUE THREAD

**Issue by PalgamingHD** [shedaniel/HQM#6]
Crash report:
https://pastebin.com/25L3j1W7

**Comment by shedaniel** [comment]
Install Cloth API.

**Comment by PalgamingHD** [comment]
We have it

**Comment by PalgamingHD** [comment]
this is weird, in game Cloth API is not showing in Mod Menu but its 100% in the mods folder.

**Comment by shedaniel** [comment]
I meant you have to install an updated version of cloth api that fixed this

https://www.curseforge.com/minecraft/mc-mods/cloth-api/files

**Comment by PalgamingHD** [comment]
ok, that version is for 1.16.2 though, and all the versions for 1.16.1 crash on the server side with HQM so idk what to do.
